.github/workflows/run_tests.yaml
Dockerfile
README.md
docker-compose.yml
scripts/run_tests.sh

add docker and gh actions unit test environment

---

dbadmin/migrations/002_drop_health_index.down.sql
dbadmin/migrations/002_drop_health_index.up.sql

drop image health_index, currently not needed

---

.github/workflows/run_linters.yaml
Dockerfile
go.mod
go.sum

Change build image to golang:latest to bump golang version to 1.18

---

Dockerfile
conf/pyxis.env
go.mod
pyxis/database.go
pyxis/profile.go
pyxis/profiles.yml
pyxis/pyxis.go
vmsync/vmsync.go

+ fixed bug with panic, rollback and uninitialized variable

add support for profiles in Pyxis gatherer and enable 'testing' profile by default

---

manager/manager.go

Add /api/vuln4shift prefix to the api endpoints

Unite api paths 

---

.github/workflows/run_tests.yaml
docker-compose.yml

Add codecov to the github actions

---

scripts/generate_swagger.sh

Fix generate_swagger.sh, use GOPATH env variable instead of HOME

---

.gitignore
manager/base/filters.go
manager/base/parsers.go
manager/controllers/cves/cves.go
manager/controllers/cves/exposed.go
manager/manager.go
manager/middlewares/filterer.go
manager/middlewares/filterer_test.go
scripts/generate_swagger.sh

Add basic /cves/:cveName/exposed_clusters api endpoint

---

manager/base/filters.go
manager/controllers/cves/base.go
manager/controllers/cves/details.go
manager/controllers/cves/exposed.go
manager/manager.go

Add basic cve details endpoint

---

README.md
manager/base/responses.go
manager/controllers/cves/cves.go
manager/controllers/cves/details.go
manager/controllers/cves/exposed.go
manager/controllers/meta/apistatus.go
manager/manager.go
scripts/3scale-mock
scripts/generate_swagger.sh

fix various manager issues

---

manager/base/filters.go
manager/controllers/cves/cves.go
manager/controllers/cves/details.go
manager/controllers/cves/exposed.go
manager/middlewares/filterer.go
manager/middlewares/filterer_test.go

manager fixes

---

manager/controllers/cves/cves.go
manager/controllers/cves/details.go
manager/controllers/cves/exposed.go
manager/manager.go

support to select HTTPS scheme in ephemeral Swagger UI

---

deploy/clowdapp.yaml

make the Swagger UI available unauthenticated

---

manager/base/filters.go
manager/controllers/cves/cves.go

add counts of affected {clusters,images} to cves endpoint

---

base/utils/kafka.go
base/utils/kafka_test.go
digestwriter/consumer.go
digestwriter/consumer_test.go
digestwriter/digestwriter.go
digestwriter/export_test.go

Move Kafka consumer code to utils package

---

base/utils/kafka.go

fix using of clowderized config

---

manager/controllers/clusters/base.go
manager/controllers/clusters/clusters.go
manager/manager.go

That is really basic clusters api

Add basic /clusters endpoint

---

digestwriter/storage.go
digestwriter/storage_test.go
scripts/3scale-mock

fix usage of FirstOrCreate and properly cast orgID

---

digestwriter/consumer.go
digestwriter/consumer_test.go
digestwriter/storage.go
digestwriter/storage_test.go
local_setup/config.yml
local_setup/sha_generator.go

- Make sha_generator also update account table if necessary with an `insert on conflict do nothing` statement
- Use where + firstOrCreate in Gorm insert operations for more robustness
- Add more logging in debug mode

Digestwriter and sha generator improvements

---

manager/base/context.go
manager/base/filters.go
manager/controllers/clusters/cves.go
manager/manager.go

- Refactored gin context helper functions to `context.go`
- Added cluster-cves endpoint and added  **complete** openapi docs

add /clusters/{cluster_id}/cves endpoint

---

Dockerfile
pr_check.sh
scripts/generate_swagger.sh

build image from dockerhub is not supported by app-sre

---

README.md

add tests and codecov badges

---

base/utils/database.go
local_setup/sha_generator.go

url escape db passwords

---

manager/controllers/clusters/cves.go
manager/controllers/cves/cves.go
manager/controllers/cves/exposed.go

add missing openapi docs

---

manager/base/controller.go
manager/controllers/clusters/base.go
manager/controllers/clusters/clusters.go
manager/controllers/cves/base.go
manager/controllers/cves/cves.go
manager/controllers/cves/details.go
manager/controllers/cves/exposed.go
manager/manager.go

manager refactor

---

README.md
deploy/clowdapp.yaml
manager/manager.go

change the base path to match stage path

---

digestwriter/consumer.go
digestwriter/consumer_test.go
digestwriter/digestwriter.go

Reverts RedHatInsights/vuln4shift-backend#63

Revert "Debug messages received by digestwriter"

---

manager/base/responses.go
manager/controllers/clusters/clusters.go
manager/controllers/clusters/cves.go
manager/controllers/cves/cves.go
manager/controllers/cves/details.go
manager/controllers/cves/exposed.go
scripts/generate_swagger.sh

seems working good now (I'm not sure why it generated incorrect references in spec previously), except one bug fixed by second commit

re-enable OpenAPI 3 conversion

---

manager/base/query.go
manager/controllers/clusters/clusters.go
manager/controllers/clusters/cves.go
manager/controllers/cves/cves.go
manager/controllers/cves/exposed.go

Previous implementation could not get count for query when the `ORDER BY` was applied. Now the list query gets queried for count and after that the paging + ordering is applied and whole query gets used.

rework manager list query

---

manager/base/filters.go

This could be a confusing for user when he sees "id" sort.

dont show default sort filters in response

---

manager/controllers/clusters/clusters.go

By this [PR](https://github.com/RedHatInsights/vuln4shift-backend/pull/61) I broke the clusters endpoint. Fixing it

fix clusters/ endpoint query

---

deploy/clowdapp.yaml
pyxis/profile.go
pyxis/profiles.yml
pyxis/pyxis.go

use 'all' instead of empty string to sync all pyxis repos, make it default in clowder deployment

---

deploy/clowdapp.yaml

remove kafka host ENV, this is not used because clowder config is preferred

---

manager/controllers/cves/cves.go

- explain analyze cost from 139 to 33, but only on my localhost

optimize /cves db query

---

digestwriter/consumer.go

This reverts commit ef9a975d97cc3773b74a42cf08eba74e141199c9.

Revert "digestwriter - Use default cluster UUID when parsed message does not contain it"

---

manager/base/filters.go
manager/base/parsers.go
manager/controllers/cves/cves.go

remove affected_images filter - affected_clusters provides the same functionality

---

base/utils/core.go
manager/base/filters.go
manager/base/query.go
manager/base/responses.go
manager/controllers/clusters/clusters.go
manager/controllers/clusters/cves.go
manager/controllers/cves/cves.go
manager/controllers/cves/details.go
manager/controllers/cves/exposed.go

Based on used filters, we can create response simpler and do not need to pass allowed filters everywhere

return used filters in response

---

manager/base/filters.go

affected_systems should respect /cves subquery

---

manager/base/parsers.go
manager/controllers/clusters/clusters.go
manager/controllers/clusters/cves.go
manager/controllers/cves/cves.go
manager/controllers/cves/exposed.go

restrict manager page limit to 100

---

manager/controllers/clusters/details.go
manager/manager.go

add cluster detail endpoint

---

manager/base/filters.go

VULN4OS-95
True,True and False.False should show all systems

ignore affected_clusters same values

---

pyxis/pyxis.go

properly delete images and repos

---

base/utils/config.go
deploy/clowdapp.yaml

rename to PROMETHEUS_PUSHGATEWAY to avoid re-mapping in app-interface config

---

.github/workflows/run_commit_messages_check.yaml
Dockerfile
build_deploy.sh
manager/manager.go
scripts/check_commit_messages.sh

chore: pass version from latest tag to manager

---

manager/controllers/clusters/clusters.go
manager/controllers/cves/exposed.go

feat(manager): add sort for display_name

---

manager/controllers/clusters/cves.go
manager/controllers/cves/cves.go

fix(manager): fix sorting for cvss2/3_score

---

deploy/clowdapp.yaml

chore(deploy): add resources to the cleaner job

---

deploy/clowdapp.yaml

chore: change cluster retention days to 31

---

pyxis/api.go
pyxis/database.go
pyxis/pyxis.go
vmsync/api.go
vmsync/database.go
vmsync/vmsync.go

fix: make sure CVEs are ordered while inserting/deleting

---

base/utils/config.go
deploy/clowdapp.yaml

feat(manager-ams-api): prepare env variables

---

manager/amsclient/amsclient.go
manager/amsclient/utils.go
manager/controllers/clusters/clusters.go
manager/controllers/cves/cves.go
manager/controllers/cves/exposed.go

ams cluster search

---

go.mod
go.sum
manager/base/filters.go
manager/base/parsers.go
manager/base/responses.go
manager/controllers/clusters/clusters.go
manager/controllers/clusters/cves.go
manager/controllers/cves/cves.go
manager/controllers/cves/exposed.go

feat(manager): add csv support for pageable endpoints

---

manager/base/responses.go
manager/controllers/clusters/clusters.go
manager/controllers/clusters/cves.go
manager/controllers/clusters/details.go
manager/controllers/cves/cves.go
manager/controllers/cves/details.go
manager/controllers/cves/exposed.go

add unique sets of statuses, versions and providers

---

base/models/models.go
dbadmin/migrations/010_cluster_type_display_name.down.sql
dbadmin/migrations/010_cluster_type_display_name.up.sql
manager/amsclient/amsclient.go
manager/amsclient/database.go
manager/amsclient/utils.go
manager/base/responses.go
manager/controllers/clusters/clusters.go
manager/controllers/cves/cves.go
manager/controllers/cves/exposed.go

AMS sync to DB

---

base/models/models.go
dbadmin/migrations/010_cluster_type_display_name.down.sql
dbadmin/migrations/010_cluster_type_display_name.up.sql
dbadmin/migrations/011_manager_update_cluster.down.sql
dbadmin/migrations/011_manager_update_cluster.up.sql
digestwriter/storage.go
manager/amsclient/amsclient.go
manager/amsclient/database.go
manager/amsclient/utils.go
manager/base/filters.go
manager/base/responses.go
manager/controllers/clusters/clusters.go
manager/controllers/cves/cves.go
manager/controllers/cves/exposed.go

Support sorting by cluster attributes

---

pyxis/api.go

fix(pyxis): return unique image cves despite errata from pyxis

---

digestwriter/consumer.go
digestwriter/storage.go

fix(digest-writer): collect digests from containers

---

pyxis/api.go

fix(pyxis): dont init array with empty values

---

manager/base/filters.go
manager/base/parsers.go
manager/base/query.go
manager/controllers/clusters/clusters.go
manager/controllers/clusters/cves.go
manager/controllers/cves/cves.go
manager/controllers/cves/exposed.go

feat(manager): add report query for returning all records

---

manager/base/filters.go
manager/base/parsers.go
manager/controllers/clusters/clusters.go

feat(manager): add cluster status filter

---

manager/base/filters.go
manager/base/parsers.go
manager/controllers/clusters/clusters.go

feat(manager): add version filter for clusters

---

manager/base/filters.go
manager/base/parsers.go
manager/controllers/clusters/clusters.go

feat(manager): add provider cluster filter

---

manager/controllers/clusters/clusters.go

feat(manager): add sorting by cve severity for clusters

---

manager/base/responses.go

fix(manager): return meta lists in predictable order

---

manager/base/parsers.go

fix(manager): report query should use parsedValues

---

deploy/clowdapp.yaml

ephemeral wont deploy manager because of this

chore: add ams secret for ephemeral

---

base/utils/kafka.go

fix(kafka): create TLS context despite empty cacert

---

go.mod
manager/base/responses.go

fix(manager): sort versions by number

---

base/models/models.go
dbadmin/migrations/014_drop_account_number.down.sql
dbadmin/migrations/014_drop_account_number.up.sql
dbadmin/testing_data.sql
digestwriter/consumer.go
digestwriter/storage.go
digestwriter/storage_test.go
local_setup/sha_generator.go

feat: account_number drop

---

pyxis/api.go
pyxis/database.go
pyxis/pyxis.go

fix(pyxis): use repository map with reg,repo key

---

base/models/models.go
cleaner/cluster_test.go
dbadmin/migrations/015_cluster_workload_info.down.sql
dbadmin/migrations/015_cluster_workload_info.up.sql
dbadmin/testing_data.sql
digestwriter/consumer.go
digestwriter/storage.go
digestwriter/storage_test.go
local_setup/sha_generator.go

feat(digestwriter): store cluster workload JSON

---

pyxis/pyxis.go

fix(pyxis): referencing attributes of apiImage will use only the last value in the loop, reference local variables instead

---

.golangci.yaml
base/utils/config.go
deploy/clowdapp.yaml
pyxis/pyxis.go

feat(pyxis): skip image CVE sync (debug purposes)

---

dbadmin/testing_data.sql
test/util.go
vmsync/database.go
vmsync/metrics.go
vmsync/vmsync.go
vmsync/vmsync_test.go

feat(vmsync): prune CVEs during sync

---

pyxis/database.go
pyxis/pyxis.go

fix(pyxis): use both pyxis_id and reg/repo key for sync

---

dbadmin/migrations/017_digestwriter_delete.down.sql
dbadmin/migrations/017_digestwriter_delete.up.sql
digestwriter/consumer.go
digestwriter/export_test.go
digestwriter/storage.go
digestwriter/storage_test.go
local_setup/config.yml
local_setup/sha_generator.go

Delete image hits

---

manager/amsclient/database.go
manager/controllers/clusters/clusters.go
manager/controllers/cves/cves.go
manager/controllers/cves/exposed.go

Return only cluster attributes related to a single CVE

---

base/ams/types.go
dbadmin/testing_data.sql
manager/amsclient/amsclient.go
manager/amsclient/amsclient_test.go
manager/controllers/clusters/clusters_test.go
manager/controllers/clusters/cves_test.go
manager/controllers/clusters/details.go
manager/controllers/clusters/details_test.go
manager/controllers/cves/cves_test.go
manager/controllers/cves/details_test.go
manager/controllers/cves/exposed_test.go
test/account.go
test/ams.go
test/cluster.go
test/cve.go
test/gin.go
test/util.go

test(manager): add manager tests

---

pyxis/pyxis.go

fix(pyxis): correct registerMissingCves metric incrementation

---

pyxis/api.go

fix(pyxis): improve repo images check

---

base/api/client_test.go
test/api.go

test(base): add API tests

---

dbadmin/testing_data.sql
pyxis/api.go
pyxis/pyxis_test.go
test/api.go
test/image.go
test/pyxis.go
test/repo.go
vmsync/vmsync_test.go

test(pyxis): add Pyxis tests

---

base/utils/config.go
base/utils/config_test.go
base/utils/core_test.go
base/utils/database_test.go
base/utils/kafka.go
base/utils/kafka_test.go
base/utils/prometheus.go
base/utils/prometheus_test.go
base/utils/scram_client_test.go

test(base): add utils tests

---

vmsync/vmsync_test.go

test(vmsync): add more unit tests

---

base/api/client_test.go
base/utils/prometheus_test.go
dbadmin/testing_data.sql
pyxis/database_test.go
pyxis/metrics_test.go
pyxis/profile_test.go
pyxis/profiles.yml
pyxis/pyxis_test.go
test/api.go
test/cve.go
test/image.go
test/image_cve.go
test/metrics.go
test/pyxis.go
test/repo.go
test/repository_image.go
vmsync/vmsync_test.go

test(pyxis): add more pyxis unit tests

---

manager/amsclient/amsclient_test.go

test(manager): add more manager unit tests

---

digestwriter/storage.go
digestwriter/storage_test.go

feat(digestwriter): add cve-cluster cache calculation

---

digestwriter/storage.go

chore(digestwriter): force cache regeneration

---

manager/controllers/cves/cves.go
manager/controllers/cves/cves_test.go

chore(manager): disable exposed images on /cves endpoint

---

manager/controllers/clusters/cves.go

chore(manager): disable exposed images on /clusers/id/cves

---

dbadmin/dbadmin.go

chore(dbadmin): remove invalid cve

---

manager/base/query.go
manager/controllers/cves/exposed_count.go
manager/controllers/cves/exposed_count_test.go
manager/manager.go
test/cve.go

feat(manager): add exposed clusters count endpoint

---

Dockerfile

chore: ubi8 now contains golang 1.18

---

base/utils/core.go
base/utils/core_test.go
pyxis/api.go

feat(pyxis): validate cves from pyxis

---

digestwriter/consumer.go
digestwriter/digestwriter.go
digestwriter/export_test.go
digestwriter/storage.go
manager/controllers/clusters/clusters.go
test/setup.go

feat(manager): use cve cluster caching

---

deploy/clowdapp.yaml

fix(expsync): add missing clowdapp env vars

---

deploy/clowdapp.yaml

chore: add exploits gatherer db pwd for ephemeral

---

deploy/clowdapp.yaml

chore: deploy amsclient as empty string in ephemeral

---

dbadmin/dbadmin.go

Discovered during debugging that `dbadmin` does not handle dirty DB state.
Completely optional right now.

chore(dbadmin): handle force migration version if database is dirty

---

pr_check.sh

Enable PR Checks in ephemeral environments using IQE

chore: enable PR Checks

---

deploy/clowdapp.yaml
pr_check.sh

- Fixes iqe plugin to correctly be installed

chore: add iqe plugin clowdapp

---

manager/base/filters.go
manager/controllers/clusters/clusters.go

fix(manager): fix references to columns in removed subquery

---

deploy/clowdapp.yaml

- change apiPath to ocp-vulnerability in clowdapp

fix: change apiPath to ocp-vulnerability

---

base/utils/kafka.go
base/utils/kafka_test.go
base/utils/payload_tracker.go
digestwriter/consumer.go
digestwriter/consumer_test.go
digestwriter/metrics.go

VULN4OS-199
- Payload Tracker metrics
- Changed go-routines to count metrics
- More Kafka tests

feat(digestwriter): add Payload Tracker metrics

---

dbadmin/dbadmin.go

chore(dbadmin): remove cve removing functionality

---

base/utils/payload_tracker.go
digestwriter/consumer.go

fix(digestwriter): pass pt message by value

---

base/utils/payload_tracker.go

chore(base): use RFC3339Nano timestamp in payload tracker messages

---

.github/workflows/run_semantic_release.yaml

fix: use older semantic-release ver

---

digestwriter/storage.go
digestwriter/storage_test.go
test/setup.go

fix(digestwriter): build cve cluster cache based on select from table

---

base/utils/payload_tracker.go
digestwriter/consumer.go
digestwriter/consumer_test.go
digestwriter/storage.go
digestwriter/storage_test.go

fix(digestwriter): accept different account number types

---

base/models/models.go
cleaner/cluster.go
cleaner/cluster_test.go
manager/amsclient/amsclient_test.go
manager/amsclient/database.go
test/cluster.go
test/cve.go

fix: don't fetch Workload JSONB to optimize memory consumption

---

digestwriter/consumer.go
digestwriter/consumer_test.go

feat: ccx-sha-extractor decompression for messages

---

go.mod

chore: bump go version to current ubi8 version

---

scripts/3scale-mock

chore: service account support in 3scale-mock

---

manager/controllers/cves/cves.go
manager/controllers/cves/cves_test.go

feat: add images_exposed to /cves

---

base/models/models.go
dbadmin/migrations/022_repository_image_tags.down.sql
dbadmin/migrations/022_repository_image_tags.up.sql
pyxis/api.go
pyxis/metrics.go
pyxis/pyxis.go
pyxis/pyxis_test.go
test/pyxis.go

feat: add tags to repository_image table

---

.github/workflows/run_commit_messages_check.yaml
.github/workflows/run_linters.yaml
.github/workflows/run_semantic_release.yaml
.github/workflows/run_tests.yaml
test/metrics.go
vmsync/database.go

chore: update github actions

---

manager/controllers/cves/base.go
manager/controllers/cves/images.go
manager/controllers/cves/images_test.go
manager/manager.go

feat: add /cves/[id]/exposed_images endpoint

---

manager/controllers/clusters/images.go
test/repository_image.go

fix(manager): unique values of cluster images

---

manager/controllers/cves/images.go
manager/controllers/cves/images_test.go

fix(manager): fix and simplify cve images query

---

manager/controllers/cves/images.go

fix(manager): count only clusters returned from amsclient

---

manager/controllers/cves/cves.go
manager/controllers/cves/cves_test.go
test/cve.go

we show all because we don't know what is running on the cluster

fix(manager): count different aliases of an image

---

dbadmin/migrations/023_missing_indexes.down.sql
dbadmin/migrations/023_missing_indexes.up.sql

fix: add indexes to improve perf when selecting from CVE and image side

---

base/models/models.go
conf/pyxis.env
dbadmin/migrations/025_single_version.down.sql
dbadmin/migrations/025_single_version.up.sql
pyxis/pyxis.go
pyxis/pyxis_test.go

fix(pyxis): store the displayed version separately

---

base/utils/gorm.go
dbadmin/testing_data.sql
manager/base/filters.go
manager/controllers/clusters/images.go
manager/controllers/clusters/images_test.go
manager/controllers/cves/images.go
manager/controllers/cves/images_test.go
test/repository_image.go

fix(manager): use version column + support sorting and filtering

---

manager/base/filters.go
manager/base/parsers.go
manager/base/query.go
manager/base/responses.go
manager/controllers/clusters/clusters.go
manager/controllers/clusters/cves.go
manager/controllers/clusters/details.go
manager/controllers/clusters/images.go
manager/controllers/cves/cves.go
manager/controllers/cves/details.go
manager/controllers/cves/exposed.go
manager/controllers/cves/images.go

filter for registry added to exposed_images pages - registry
all registry options returned in meta section - image_registries_all
RHINENG-8259

feat(manager): registry filtering

---

digestwriter/storage.go

fix(digestwriter): refresh cluster CVE cache on each check-in

---

digestwriter/consumer_test.go
test/cve.go

fixes in tests

---

deploy/clowdapp.yaml

chore: add sha-extractor as a dependency

---

expsync/database.go

fix(expsync): possible SQL injection

---

cleaner/cluster.go
manager/amsclient/database.go
test/cve.go

https://gorm.io/docs/advanced_query.html\#smart_select
RHINENG-11447

fix(gorm): force gorm to select specific fields

---

base/models/models.go
dbadmin/migrations/026_registry_repository_version.down.sql
dbadmin/migrations/026_registry_repository_version.up.sql
dbadmin/testing_data.sql
manager/base/filters.go
pyxis/pyxis.go

fix(db): store registry_repository_version with index for searching

---

manager/amsclient/database.go

https://gorm.io/docs/advanced_query.html\#smart_select
RHINENG-11447

fix(gorm): select fields with QueryFields

---

deploy/clowdapp.yaml

chore: fix resources env vars

---

go.mod
go.sum

[RHINENG-2524]
[RHINENG-2533]
[RHINENG-2540]

Update dependencies to resolve vulnerabilities

---

Dockerfile

chore: update to ubi9

---

vmsync/api.go
vmsync/vmsync.go
vmsync/vmsync_test.go

fix(vmsync): handle empty time returned from VMaaS

---

deploy/clowdapp.yaml

DO NOT MERGE BEFORE THE APP-INTERFACE MR

feat(clowder): consume container image from Konflux

---

.github/workflows/run_semantic_release.yaml
pyproject.toml
scripts/check_commit_messages.sh
setup.cfg

going to enable Konflux image build only for tags

ci: update python-semantic-release and create patch tag for more keywords

---

.tekton/vuln4shift-backend-push.yaml

ci: only build tagged commits

---

.tekton/vuln4shift-backend-pull-request.yaml
.tekton/vuln4shift-backend-push.yaml

ci: add new mandatory RPM signature scan task to tekton

---

deploy/clowdapp.yaml

minReplicas is deprecated https://redhatinsights.github.io/clowder/clowder/dev/api_reference.html\#k8s-api-github-com-redhatinsights-clowder-apis-cloud-redhat-com-v1alpha1-deployment

chore: use replicase instead of minReplicas

---

Dockerfile
README.md
conf/db.env
conf/tests.env
dbadmin/migrations/028_pg_repack.down.sql
dbadmin/migrations/028_pg_repack.up.sql
deploy/clowdapp.yaml
dev/database/Dockerfile
docker-compose.yml
main.go
repack/repack.go

feat: add pg_repack cronjob

---

deploy/clowdapp.yaml

fix(repack): use correct entrypoint

---

repack/repack.go

rather do nothing than kill transactions

fix(repack): give 600s timeout to acquire exclusive lock and skip repack if not succeeded

---

go.mod
go.sum

chore: update golang-jwt

---

.github/workflows/run_linters.yaml
.golangci.yaml
go.mod

chore: upgrade golang requirement and linter

---

.tekton/vuln4shift-backend-pull-request.yaml
.tekton/vuln4shift-backend-push.yaml

chore: bump konflux pipelines version
